### ISSUE TITLE
When using naabu as a library, an error occurs: no free handlers

### ISSUE THREAD

**Issue by M1k0er** [projectdiscovery/naabu#1040]
When I use naabu as a library on Windows, the output is successful and I get the results I want. However, when I run the same operation on Linux, it reports: no free handlers. I don’t know why.
this is my test code:

```
import (
	"github.com/projectdiscovery/naabu/v2/pkg/result"
	"github.com/projectdiscovery/naabu/v2/pkg/runner"
)
func main() {
	var HostPortList []string
	for _, r := range []string{"wlj.com.cn", "sp.wlj.com.cn", "www.wlj.com.cn", "oa.wlj.com.cn"} {
		portsToScan := "80,443"
		options := runner.Options{
			Host:     goflags.StringSlice{r},
			ScanType: "s",
			Verbose:  true,
			Debug:    true,
			OnResult: func(hr *result.HostResult) {
				for _, port := range hr.Ports {
					foundPort := strconv.Itoa(port.Port)
					HostPort := fmt.Sprintf("%s:%s", hr.Host, foundPort)
					HostPortList = append(HostPortList, HostPort)
				}
			},
			Ports:  portsToScan,
			Silent: true,
		}

		naabuRunner, err := runner.NewRunner(&options)
		if err != nil {
			log.Fatal(err)
		}
		defer naabuRunner.Close()

		naabuRunner.RunEnumeration(context.TODO())

	}
	fmt.Println("Found ports:", HostPortList)
}
```

This is the result of my running on window：

![image](https://github.com/projectdiscovery/naabu/assets/18186758/7febbf9f-901c-4c57-884b-c4c5f74a2a85)

This is the result of my running on linux：
![image](https://github.com/projectdiscovery/naabu/assets/18186758/a2292293-cee6-4936-a2f9-5eb670501613)

**Comment by faint-star** [comment]
Hello，I meet the same problem：
```
[ERR] no free handlers
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1d6afd7]

goroutine 113 [running]:
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).Close(0x0)
	/go/server/vendor/github.com/projectdiscovery/naabu/v2/pkg/runner/runner.go:659 +0x17
panic({0x24007c0?, 0x4ee5370?})
	/go/go1.21.7/src/runtime/panic.go:914 +0x21f
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).RunEnumeration(0x0, {0x3adead0?, 0x5700740?})
	/go/server/vendor/github.com/projectdiscovery/naabu/v2/pkg/runner/runner.go:249 +0x8e
```
As my test, it will occur when run as root in Linux, when I run code in windows without administrator or linux without root, it work normal
