### ISSUE TITLE
[Bug] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/naabu#148]
**Describe the bug**

**To Reproduce**
`./naabu -host notavalidhost.com `

<details>
<summary>Panic error</summary>

```yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x1033b43d8]

goroutine 1 [running]:
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).Lookup(0x140001122c0, 0x14000038210, 0x11, 0x0, 0x0, 0x14000130020, 0x1034a9ce0, 0x103575310)
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.0.1/libs/dnsx/dnsx.go:57 +0xe8
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).host2ips(0x14000088660, 0x14000038210, 0x11, 0xa0, 0x140000a36d8, 0x102fd1568, 0x140000a3678, 0x102fce368)
	/Users/geekboy/Github/naabu/v2/pkg/runner/util.go:22 +0x24c
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).resolveFQDN(0x14000088660, 0x14000038210, 0x11, 0x0, 0x0, 0x0, 0x103582298, 0x14000112300)
	/Users/geekboy/Github/naabu/v2/pkg/runner/targets.go:136 +0x40
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).AddTarget(0x14000088660, 0x14000038210, 0x11, 0x0, 0x1041a86e0)
	/Users/geekboy/Github/naabu/v2/pkg/runner/targets.go:121 +0x224
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).PreProcessTargets.func1(0x140001122e0, 0x14000088660, 0x14000038210, 0x11)
	/Users/geekboy/Github/naabu/v2/pkg/runner/targets.go:97 +0x60
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).PreProcessTargets(0x14000088660, 0x0, 0x0)
	/Users/geekboy/Github/naabu/v2/pkg/runner/targets.go:100 +0x1a4
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).Load(0x14000088660, 0x140001122c0, 0x103885f20)
	/Users/geekboy/Github/naabu/v2/pkg/runner/targets.go:29 +0x6c
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).RunEnumeration(0x14000088660, 0x14000088660, 0x0)
	/Users/geekboy/Github/naabu/v2/pkg/runner/runner.go:109 +0x60
main.main()
	/Users/geekboy/Github/naabu/v2/cmd/naabu/main.go:18 +0x40
```
</details>

**Version**
dev version

**Comment by Mzack9999** [comment]
Fixed in https://github.com/projectdiscovery/dnsx/pull/59

**Comment by ehsandeep** [comment]
Fixed in the development version with https://github.com/projectdiscovery/naabu/pull/160
